---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serv
spec:
  selector:
    matchLabels:
      app: serv
  template:
    metadata:
      labels:
        app: serv
    spec:
      containers:
      - name: serv
        image: bonnie.ops/sites/serv:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: serv-service
spec:
  type: NodePort
  selector:
    app: serv
  ports:
  - port: 8080
    nodePort: 32125
